language: node_js
node_js:
    - stable
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g gulp-cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    local_dir: build
    keep_history: true
    on:
        branch: master
env:
    global:
        secure: q1+3BqDuABADajJxW2iQpmyjEYSEkZIm6RWIsHt++xHVNQWB8uaJ3QlitmCa7YlcLK4sCDYSRNtKlrM6pplspxw+ixI+B6/nA3x7l4x1OII7b80HbMjJOAMfx/dc93CYFbKBaY6HRHl4iQp1Jm0Z2Ced+xRgRo/SeKNWr/2DbODyqC5h9zct1kjbp4Y8l3wnkg8O3UsEgP5P5LL8Z7TYa/H5vhDwR5ue1ua+/U7sPNRjLzKCFCPH+FP7Ffra2IsRqbzL0AIsBrdgD/dPw0d0IetYZ73QeaHP9rc99/x3SNL++n9/QuoSOqkX3rwl5f0R0/6qdoBHCRHyllWDUocwvF9BLYlyZuYb/J6aBkQaiMOvXM2dSza02Qfj82391VDBJuAjW93U+jm2xP6e76bamFSuEdjTp+YdA2Niv+IGB3g/WVALSDmjglUUGu3kq6JFyPGFdUR2PwVIazqfJJBGnPCCnJ+FPbwN6x2LZL5Tgf398z364WRFAn8nXKTsPh4/GbUObHkAXOouzCG25rprbfdAJhF1HvHS9qmIez/9ONC6JmZ0aonfKuP6YBVkWONUTEJFdPh24qVUaIqGTIswjcjAyeZrPnD6ztqRZoM3lywUv39DPLfGu+Cf5i67j2walAG0GH7s4tGKXC2spwIdkSihpyELnrK1AqeUjMT7NAs=
